### ISSUE TITLE
Posting examples

### ISSUE THREAD

**Issue by sanari1** [luno/luno-python#35]
Adding examples on how to do post_limit_order and post_market_order.

My attempts fail for c.post_market_order('ETHZAR','SELL') I get the following: 
  File "C:\Users\chase\anaconda3\lib\site-packages\luno_python\client.py", line 655, in post_market_order
    return self.do('POST', '/api/1/marketorder', req=req, auth=True)

  File "C:\Users\chase\anaconda3\lib\site-packages\luno_python\base_client.py", line 86, in do
    raise APIError(e['error_code'], e['error'])

APIError: ('ErrInvalidBaseVolume', 'Invalid base volume for sell order.')

and for c.post_limit_order('ETHZAR', str(price-100), 'ASK', float(ETH)) I get:

  File "C:\Users\chase\OneDrive\bot code\awesome-DESKTOP-9UVSN7B.py", line 135, in <module>
    c.post_limit_order('ETHZAR', str(price-100), 'ASK', float(ETH))

  File "C:\Users\chase\anaconda3\lib\site-packages\luno_python\client.py", line 609, in post_limit_order
    return self.do('POST', '/api/1/postorder', req=req, auth=True)

  File "C:\Users\chase\anaconda3\lib\site-packages\luno_python\base_client.py", line 86, in do
    raise APIError(e['error_code'], e['error'])

APIError: ('ErrInvalidArguments', 'One or more arguments are invalid')

**Comment by YinYin-blip** [comment]
@sanari1 For the post_market_order function, I suspect that you may need to specify either a base_volume or counter_volume; at the moment the request only knows what crypto you want to market buy but doesn't know how much to buy and I don't think the default functionality is to buy as much as your wallet balance allows.

For the post_limit_order, I can't see what the issue could be but based on the error message... it seems to not like the arguments sent. Is it possible that you could print the values and data types for the payload that is sent in the request?

**Comment by sanari1** [comment]
@YinYin-blip  You are correct I forgot that I posted this issue. I found that the problem was that if the number has more numbers after a certain decimal point it would throw the error I.E 0.005 is okay but 0.0051 was not. Also, you needed to meet a minimum number 1st. Thanks for getting back to me.

**Comment by YinYin-blip** [comment]
Glad that you have things sorted. 

Doesn't look like there is any comment or documentation about the minimum buy amount or the precision required by the server. Also, the server's return message is vague.

To avoid similar confusion in future - we could:

1. Update this client (either through documentation or handling the error on the client side)
2. Or, try get Luno to update their server to provide a more descriptive error code / message.

I prefer (2) since it doesn't require updating the client when the server requirements change, but I don't know how easy it would be to get our homies (@NeilLuno ) to update their server to check which arguments are invalid and return a more descriptive message 🤔
