### ISSUE TITLE
How to set Volume Max for post limit order?

### ISSUE THREAD

**Issue by uyin85** [luno/luno-python#36]
Hi,

I want to know how to set Volume as Max for post limit order?

**Comment by YinYin-blip** [comment]
As far as I can see the client doesn't offer any `max_volume` in this client nor does the server seem to have that kind of functionality available.

Happy to try problem solve this with you but you need to give more specific information:

- What else have you tried and how did it not work?
- Is there a small amount of ZAR or Crypto in your account that you want to remove? (don't think this is something that can be stopped)
- What happens when you create a limit order for the maximum amount of ZAR / Crypto balance that you have?

**Comment by uyin85** [comment]
Ok. I already found how to make max volume same like you click max button in platform
