### ISSUE TITLE
tt1 is an unexpected argument

### ISSUE THREAD

**Issue by spicybuns** [luno/luno-python#46]
Hi,

I am trying to code post_limit_order with tt1 argument. Somehow I get an error saying "Client.post_limit_order() got an unexpected keyword argument 'tt1'".

I am wondering this tt1 is it meant for canceling a limit order after a certain amount of time has exceeded (specify by tt1) ?

Thanks.

**Comment by YinYin-blip** [comment]
`pair, price, type, volume` are the only required arguments for `post_limit_order`. I think you are getting the error because you are passing a variable tt1 (tt[one]) instead of ttl.

I don't know the server-side is implemented, but I interpreted the ttl variable as referring to the network aspect of the request (ref: https://www.cloudflare.com/learning/cdn/glossary/time-to-live-ttl/).

**Comment by spicybuns** [comment]
Thanks YinYin-blip.
